version: '3'

services:
  dev:
    image: lvinkim/php-env-docker:latest
    ports:
      - 6600:8080
    volumes:
      - .:/var/www/html
      - ./xdebug.ini:/etc/php/7.2/mods-available/xdebug.ini
    working_dir: /var/www/html
    restart: always
    command:
      - php
      - bin/console.php
      - swim:dev:start
